nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: libs/yarn-plugin-changed/bundles/@yarnpkg/plugin-changed.js
    spec: '@liuli-util/yarn-plugin-changed'

yarnPath: .yarn/releases/yarn-berry.cjs
