compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@liuli-util/plugin-changed.cjs
    spec: libs/yarn-plugin-changed/bundles/@liuli-util/plugin-changed.js

yarnPath: .yarn/releases/yarn-berry.cjs
