query findRepoStar($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
    stargazerCount
  }
}

query findRepo($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
  }
}
