name: ci-hello

on:
  push:
    branches:
      - feat_ci

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./.yarn-cache.json
            ./**/dist/**
          key: ${{ runner.os }}-setup-${{ hashFiles('./.yarn-cache.json') }}
      - run: yarn
      - run: yarn setup
#       - run: yarn esno ./scripts/ci-deploy-remote.ts
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GIT_EMAIL: ${{ secrets.MY_EMAIL }}
#           GIT_NAME: ${{ secrets.MY_NAME }}
