name: Node.js Package

on:
  push:
    tags:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
#       - run: yarn setup
      - run: yarn esno ./scripts/ci-deploy-remote.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: ${{ secrets.MY_EMAIL }}
          GIT_NAME: ${{ secrets.MY_NAME }}
