# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: monoepo-ci

on:
  push:
    branches:
      - master
  label:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            .yarn-cache.json
          key: ${{ runner.os }}-
      - name: setup
        run: |
          yarn setup
